# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.models.apply_trust_change200_response import ApplyTrustChange200Response

class TestApplyTrustChange200Response(unittest.TestCase):
    """ApplyTrustChange200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyTrustChange200Response:
        """Test ApplyTrustChange200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyTrustChange200Response`
        """
        model = ApplyTrustChange200Response()
        if include_optional:
            return ApplyTrustChange200Response(
                previous_score = 56,
                new_score = 56,
                previous_tier = '',
                new_tier = '',
                tier_changed = True
            )
        else:
            return ApplyTrustChange200Response(
        )
        """

    def testApplyTrustChange200Response(self):
        """Test ApplyTrustChange200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
