# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Create webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete webhook
        """
        pass

    def test_get_webhook(self) -> None:
        """Test case for get_webhook

        Get webhook
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List webhooks
        """
        pass

    def test_test_webhook(self) -> None:
        """Test case for test_webhook

        Test webhook
        """
        pass

    def test_update_webhook(self) -> None:
        """Test case for update_webhook

        Update webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
