# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.models.truth_chain_record import TruthChainRecord

class TestTruthChainRecord(unittest.TestCase):
    """TruthChainRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TruthChainRecord:
        """Test TruthChainRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TruthChainRecord`
        """
        model = TruthChainRecord()
        if include_optional:
            return TruthChainRecord(
                id = '',
                sequence = 56,
                record_type = 'council_decision',
                agent_id = '',
                hash = '',
                previous_hash = '',
                data = None,
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return TruthChainRecord(
        )
        """

    def testTruthChainRecord(self):
        """Test TruthChainRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
