# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.api.notifications_api import NotificationsApi


class TestNotificationsApi(unittest.TestCase):
    """NotificationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NotificationsApi()

    def tearDown(self) -> None:
        pass

    def test_list_notifications(self) -> None:
        """Test case for list_notifications

        List notifications
        """
        pass

    def test_mark_notifications_read(self) -> None:
        """Test case for mark_notifications_read

        Mark notifications read
        """
        pass


if __name__ == '__main__':
    unittest.main()
