# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.models.list_marketplace_listings200_response import ListMarketplaceListings200Response

class TestListMarketplaceListings200Response(unittest.TestCase):
    """ListMarketplaceListings200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListMarketplaceListings200Response:
        """Test ListMarketplaceListings200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListMarketplaceListings200Response`
        """
        model = ListMarketplaceListings200Response()
        if include_optional:
            return ListMarketplaceListings200Response(
                data = [
                    agentanchor.models.marketplace_listing.MarketplaceListing(
                        id = '', 
                        agent_id = '', 
                        trainer_id = '', 
                        title = '', 
                        description = '', 
                        price_type = 'free', 
                        price_amount = 1.337, 
                        commission_rate = 1.337, 
                        status = 'draft', 
                        avg_rating = 1.337, 
                        total_acquisitions = 56, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                meta = agentanchor.models.pagination_meta.PaginationMeta(
                    page = 56, 
                    limit = 56, 
                    total = 56, 
                    has_more = True, )
            )
        else:
            return ListMarketplaceListings200Response(
        )
        """

    def testListMarketplaceListings200Response(self):
        """Test ListMarketplaceListings200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
