# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.models.create_truth_chain_record_request import CreateTruthChainRecordRequest

class TestCreateTruthChainRecordRequest(unittest.TestCase):
    """CreateTruthChainRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTruthChainRecordRequest:
        """Test CreateTruthChainRecordRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTruthChainRecordRequest`
        """
        model = CreateTruthChainRecordRequest()
        if include_optional:
            return CreateTruthChainRecordRequest(
                record_type = '',
                agent_id = '',
                data = None
            )
        else:
            return CreateTruthChainRecordRequest(
                record_type = '',
                data = None,
        )
        """

    def testCreateTruthChainRecordRequest(self):
        """Test CreateTruthChainRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
