# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.models.trust_change import TrustChange

class TestTrustChange(unittest.TestCase):
    """TrustChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TrustChange:
        """Test TrustChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TrustChange`
        """
        model = TrustChange()
        if include_optional:
            return TrustChange(
                agent_id = '',
                change_amount = -100,
                reason = '',
                category = 'council_decision',
                reference_id = ''
            )
        else:
            return TrustChange(
                agent_id = '',
                change_amount = -100,
                reason = '',
                category = 'council_decision',
        )
        """

    def testTrustChange(self):
        """Test TrustChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
