# coding: utf-8

"""
    AgentAnchor API

    AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentanchor.models.list_anomalies200_response import ListAnomalies200Response

class TestListAnomalies200Response(unittest.TestCase):
    """ListAnomalies200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAnomalies200Response:
        """Test ListAnomalies200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAnomalies200Response`
        """
        model = ListAnomalies200Response()
        if include_optional:
            return ListAnomalies200Response(
                data = [
                    None
                    ]
            )
        else:
            return ListAnomalies200Response(
        )
        """

    def testListAnomalies200Response(self):
        """Test ListAnomalies200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
