/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
)

// checks if the ListAcquisitions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAcquisitions200Response{}

// ListAcquisitions200Response struct for ListAcquisitions200Response
type ListAcquisitions200Response struct {
	Data []Acquisition `json:"data,omitempty"`
}

// NewListAcquisitions200Response instantiates a new ListAcquisitions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAcquisitions200Response() *ListAcquisitions200Response {
	this := ListAcquisitions200Response{}
	return &this
}

// NewListAcquisitions200ResponseWithDefaults instantiates a new ListAcquisitions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAcquisitions200ResponseWithDefaults() *ListAcquisitions200Response {
	this := ListAcquisitions200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListAcquisitions200Response) GetData() []Acquisition {
	if o == nil || IsNil(o.Data) {
		var ret []Acquisition
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListAcquisitions200Response) GetDataOk() ([]Acquisition, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListAcquisitions200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Acquisition and assigns it to the Data field.
func (o *ListAcquisitions200Response) SetData(v []Acquisition) {
	o.Data = v
}

func (o ListAcquisitions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAcquisitions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListAcquisitions200Response struct {
	value *ListAcquisitions200Response
	isSet bool
}

func (v NullableListAcquisitions200Response) Get() *ListAcquisitions200Response {
	return v.value
}

func (v *NullableListAcquisitions200Response) Set(val *ListAcquisitions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAcquisitions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAcquisitions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAcquisitions200Response(val *ListAcquisitions200Response) *NullableListAcquisitions200Response {
	return &NullableListAcquisitions200Response{value: val, isSet: true}
}

func (v NullableListAcquisitions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAcquisitions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


