/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
)

// checks if the GetAgent200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAgent200Response{}

// GetAgent200Response struct for GetAgent200Response
type GetAgent200Response struct {
	Data *Agent `json:"data,omitempty"`
}

// NewGetAgent200Response instantiates a new GetAgent200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAgent200Response() *GetAgent200Response {
	this := GetAgent200Response{}
	return &this
}

// NewGetAgent200ResponseWithDefaults instantiates a new GetAgent200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAgent200ResponseWithDefaults() *GetAgent200Response {
	this := GetAgent200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAgent200Response) GetData() Agent {
	if o == nil || IsNil(o.Data) {
		var ret Agent
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAgent200Response) GetDataOk() (*Agent, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAgent200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Agent and assigns it to the Data field.
func (o *GetAgent200Response) SetData(v Agent) {
	o.Data = &v
}

func (o GetAgent200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAgent200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetAgent200Response struct {
	value *GetAgent200Response
	isSet bool
}

func (v NullableGetAgent200Response) Get() *GetAgent200Response {
	return v.value
}

func (v *NullableGetAgent200Response) Set(val *GetAgent200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAgent200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAgent200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAgent200Response(val *GetAgent200Response) *NullableGetAgent200Response {
	return &NullableGetAgent200Response{value: val, isSet: true}
}

func (v NullableGetAgent200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAgent200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


