/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
)

// checks if the ApplyTrustChange200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplyTrustChange200Response{}

// ApplyTrustChange200Response struct for ApplyTrustChange200Response
type ApplyTrustChange200Response struct {
	PreviousScore *int32 `json:"previous_score,omitempty"`
	NewScore *int32 `json:"new_score,omitempty"`
	PreviousTier *string `json:"previous_tier,omitempty"`
	NewTier *string `json:"new_tier,omitempty"`
	TierChanged *bool `json:"tier_changed,omitempty"`
}

// NewApplyTrustChange200Response instantiates a new ApplyTrustChange200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplyTrustChange200Response() *ApplyTrustChange200Response {
	this := ApplyTrustChange200Response{}
	return &this
}

// NewApplyTrustChange200ResponseWithDefaults instantiates a new ApplyTrustChange200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplyTrustChange200ResponseWithDefaults() *ApplyTrustChange200Response {
	this := ApplyTrustChange200Response{}
	return &this
}

// GetPreviousScore returns the PreviousScore field value if set, zero value otherwise.
func (o *ApplyTrustChange200Response) GetPreviousScore() int32 {
	if o == nil || IsNil(o.PreviousScore) {
		var ret int32
		return ret
	}
	return *o.PreviousScore
}

// GetPreviousScoreOk returns a tuple with the PreviousScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTrustChange200Response) GetPreviousScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.PreviousScore) {
		return nil, false
	}
	return o.PreviousScore, true
}

// HasPreviousScore returns a boolean if a field has been set.
func (o *ApplyTrustChange200Response) HasPreviousScore() bool {
	if o != nil && !IsNil(o.PreviousScore) {
		return true
	}

	return false
}

// SetPreviousScore gets a reference to the given int32 and assigns it to the PreviousScore field.
func (o *ApplyTrustChange200Response) SetPreviousScore(v int32) {
	o.PreviousScore = &v
}

// GetNewScore returns the NewScore field value if set, zero value otherwise.
func (o *ApplyTrustChange200Response) GetNewScore() int32 {
	if o == nil || IsNil(o.NewScore) {
		var ret int32
		return ret
	}
	return *o.NewScore
}

// GetNewScoreOk returns a tuple with the NewScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTrustChange200Response) GetNewScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.NewScore) {
		return nil, false
	}
	return o.NewScore, true
}

// HasNewScore returns a boolean if a field has been set.
func (o *ApplyTrustChange200Response) HasNewScore() bool {
	if o != nil && !IsNil(o.NewScore) {
		return true
	}

	return false
}

// SetNewScore gets a reference to the given int32 and assigns it to the NewScore field.
func (o *ApplyTrustChange200Response) SetNewScore(v int32) {
	o.NewScore = &v
}

// GetPreviousTier returns the PreviousTier field value if set, zero value otherwise.
func (o *ApplyTrustChange200Response) GetPreviousTier() string {
	if o == nil || IsNil(o.PreviousTier) {
		var ret string
		return ret
	}
	return *o.PreviousTier
}

// GetPreviousTierOk returns a tuple with the PreviousTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTrustChange200Response) GetPreviousTierOk() (*string, bool) {
	if o == nil || IsNil(o.PreviousTier) {
		return nil, false
	}
	return o.PreviousTier, true
}

// HasPreviousTier returns a boolean if a field has been set.
func (o *ApplyTrustChange200Response) HasPreviousTier() bool {
	if o != nil && !IsNil(o.PreviousTier) {
		return true
	}

	return false
}

// SetPreviousTier gets a reference to the given string and assigns it to the PreviousTier field.
func (o *ApplyTrustChange200Response) SetPreviousTier(v string) {
	o.PreviousTier = &v
}

// GetNewTier returns the NewTier field value if set, zero value otherwise.
func (o *ApplyTrustChange200Response) GetNewTier() string {
	if o == nil || IsNil(o.NewTier) {
		var ret string
		return ret
	}
	return *o.NewTier
}

// GetNewTierOk returns a tuple with the NewTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTrustChange200Response) GetNewTierOk() (*string, bool) {
	if o == nil || IsNil(o.NewTier) {
		return nil, false
	}
	return o.NewTier, true
}

// HasNewTier returns a boolean if a field has been set.
func (o *ApplyTrustChange200Response) HasNewTier() bool {
	if o != nil && !IsNil(o.NewTier) {
		return true
	}

	return false
}

// SetNewTier gets a reference to the given string and assigns it to the NewTier field.
func (o *ApplyTrustChange200Response) SetNewTier(v string) {
	o.NewTier = &v
}

// GetTierChanged returns the TierChanged field value if set, zero value otherwise.
func (o *ApplyTrustChange200Response) GetTierChanged() bool {
	if o == nil || IsNil(o.TierChanged) {
		var ret bool
		return ret
	}
	return *o.TierChanged
}

// GetTierChangedOk returns a tuple with the TierChanged field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApplyTrustChange200Response) GetTierChangedOk() (*bool, bool) {
	if o == nil || IsNil(o.TierChanged) {
		return nil, false
	}
	return o.TierChanged, true
}

// HasTierChanged returns a boolean if a field has been set.
func (o *ApplyTrustChange200Response) HasTierChanged() bool {
	if o != nil && !IsNil(o.TierChanged) {
		return true
	}

	return false
}

// SetTierChanged gets a reference to the given bool and assigns it to the TierChanged field.
func (o *ApplyTrustChange200Response) SetTierChanged(v bool) {
	o.TierChanged = &v
}

func (o ApplyTrustChange200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplyTrustChange200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PreviousScore) {
		toSerialize["previous_score"] = o.PreviousScore
	}
	if !IsNil(o.NewScore) {
		toSerialize["new_score"] = o.NewScore
	}
	if !IsNil(o.PreviousTier) {
		toSerialize["previous_tier"] = o.PreviousTier
	}
	if !IsNil(o.NewTier) {
		toSerialize["new_tier"] = o.NewTier
	}
	if !IsNil(o.TierChanged) {
		toSerialize["tier_changed"] = o.TierChanged
	}
	return toSerialize, nil
}

type NullableApplyTrustChange200Response struct {
	value *ApplyTrustChange200Response
	isSet bool
}

func (v NullableApplyTrustChange200Response) Get() *ApplyTrustChange200Response {
	return v.value
}

func (v *NullableApplyTrustChange200Response) Set(val *ApplyTrustChange200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApplyTrustChange200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApplyTrustChange200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplyTrustChange200Response(val *ApplyTrustChange200Response) *NullableApplyTrustChange200Response {
	return &NullableApplyTrustChange200Response{value: val, isSet: true}
}

func (v NullableApplyTrustChange200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplyTrustChange200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


