/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateMarketplaceListingRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMarketplaceListingRequest{}

// CreateMarketplaceListingRequest struct for CreateMarketplaceListingRequest
type CreateMarketplaceListingRequest struct {
	AgentId string `json:"agent_id"`
	Title string `json:"title"`
	Description *string `json:"description,omitempty"`
	PriceType string `json:"price_type"`
	PriceAmount *float32 `json:"price_amount,omitempty"`
	CommissionRate *float32 `json:"commission_rate,omitempty"`
}

type _CreateMarketplaceListingRequest CreateMarketplaceListingRequest

// NewCreateMarketplaceListingRequest instantiates a new CreateMarketplaceListingRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMarketplaceListingRequest(agentId string, title string, priceType string) *CreateMarketplaceListingRequest {
	this := CreateMarketplaceListingRequest{}
	this.AgentId = agentId
	this.Title = title
	this.PriceType = priceType
	return &this
}

// NewCreateMarketplaceListingRequestWithDefaults instantiates a new CreateMarketplaceListingRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMarketplaceListingRequestWithDefaults() *CreateMarketplaceListingRequest {
	this := CreateMarketplaceListingRequest{}
	return &this
}

// GetAgentId returns the AgentId field value
func (o *CreateMarketplaceListingRequest) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *CreateMarketplaceListingRequest) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *CreateMarketplaceListingRequest) SetAgentId(v string) {
	o.AgentId = v
}

// GetTitle returns the Title field value
func (o *CreateMarketplaceListingRequest) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreateMarketplaceListingRequest) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreateMarketplaceListingRequest) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateMarketplaceListingRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMarketplaceListingRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateMarketplaceListingRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateMarketplaceListingRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPriceType returns the PriceType field value
func (o *CreateMarketplaceListingRequest) GetPriceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PriceType
}

// GetPriceTypeOk returns a tuple with the PriceType field value
// and a boolean to check if the value has been set.
func (o *CreateMarketplaceListingRequest) GetPriceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PriceType, true
}

// SetPriceType sets field value
func (o *CreateMarketplaceListingRequest) SetPriceType(v string) {
	o.PriceType = v
}

// GetPriceAmount returns the PriceAmount field value if set, zero value otherwise.
func (o *CreateMarketplaceListingRequest) GetPriceAmount() float32 {
	if o == nil || IsNil(o.PriceAmount) {
		var ret float32
		return ret
	}
	return *o.PriceAmount
}

// GetPriceAmountOk returns a tuple with the PriceAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMarketplaceListingRequest) GetPriceAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.PriceAmount) {
		return nil, false
	}
	return o.PriceAmount, true
}

// HasPriceAmount returns a boolean if a field has been set.
func (o *CreateMarketplaceListingRequest) HasPriceAmount() bool {
	if o != nil && !IsNil(o.PriceAmount) {
		return true
	}

	return false
}

// SetPriceAmount gets a reference to the given float32 and assigns it to the PriceAmount field.
func (o *CreateMarketplaceListingRequest) SetPriceAmount(v float32) {
	o.PriceAmount = &v
}

// GetCommissionRate returns the CommissionRate field value if set, zero value otherwise.
func (o *CreateMarketplaceListingRequest) GetCommissionRate() float32 {
	if o == nil || IsNil(o.CommissionRate) {
		var ret float32
		return ret
	}
	return *o.CommissionRate
}

// GetCommissionRateOk returns a tuple with the CommissionRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMarketplaceListingRequest) GetCommissionRateOk() (*float32, bool) {
	if o == nil || IsNil(o.CommissionRate) {
		return nil, false
	}
	return o.CommissionRate, true
}

// HasCommissionRate returns a boolean if a field has been set.
func (o *CreateMarketplaceListingRequest) HasCommissionRate() bool {
	if o != nil && !IsNil(o.CommissionRate) {
		return true
	}

	return false
}

// SetCommissionRate gets a reference to the given float32 and assigns it to the CommissionRate field.
func (o *CreateMarketplaceListingRequest) SetCommissionRate(v float32) {
	o.CommissionRate = &v
}

func (o CreateMarketplaceListingRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMarketplaceListingRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_id"] = o.AgentId
	toSerialize["title"] = o.Title
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["price_type"] = o.PriceType
	if !IsNil(o.PriceAmount) {
		toSerialize["price_amount"] = o.PriceAmount
	}
	if !IsNil(o.CommissionRate) {
		toSerialize["commission_rate"] = o.CommissionRate
	}
	return toSerialize, nil
}

func (o *CreateMarketplaceListingRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_id",
		"title",
		"price_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMarketplaceListingRequest := _CreateMarketplaceListingRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateMarketplaceListingRequest)

	if err != nil {
		return err
	}

	*o = CreateMarketplaceListingRequest(varCreateMarketplaceListingRequest)

	return err
}

type NullableCreateMarketplaceListingRequest struct {
	value *CreateMarketplaceListingRequest
	isSet bool
}

func (v NullableCreateMarketplaceListingRequest) Get() *CreateMarketplaceListingRequest {
	return v.value
}

func (v *NullableCreateMarketplaceListingRequest) Set(val *CreateMarketplaceListingRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMarketplaceListingRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMarketplaceListingRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMarketplaceListingRequest(val *CreateMarketplaceListingRequest) *NullableCreateMarketplaceListingRequest {
	return &NullableCreateMarketplaceListingRequest{value: val, isSet: true}
}

func (v NullableCreateMarketplaceListingRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMarketplaceListingRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


