/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
	"time"
)

// checks if the Agent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Agent{}

// Agent struct for Agent
type Agent struct {
	// Unique agent identifier
	Id *string `json:"id,omitempty"`
	// Agent display name
	Name *string `json:"name,omitempty"`
	// Agent description
	Description *string `json:"description,omitempty"`
	// Current agent status
	Status *string `json:"status,omitempty"`
	// Current trust score (0-1000)
	TrustScore *int32 `json:"trust_score,omitempty"`
	// Trust tier based on score
	TrustTier *string `json:"trust_tier,omitempty"`
	// Council certification level
	CertificationLevel *string `json:"certification_level,omitempty"`
	// Whether agent is listed on marketplace
	Published *bool `json:"published,omitempty"`
	// List of agent capabilities
	Capabilities []string `json:"capabilities,omitempty"`
	// Creation timestamp
	CreatedAt *time.Time `json:"created_at,omitempty"`
}

// NewAgent instantiates a new Agent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgent() *Agent {
	this := Agent{}
	return &this
}

// NewAgentWithDefaults instantiates a new Agent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentWithDefaults() *Agent {
	this := Agent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Agent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Agent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Agent) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Agent) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Agent) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Agent) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Agent) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Agent) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Agent) SetDescription(v string) {
	o.Description = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Agent) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Agent) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Agent) SetStatus(v string) {
	o.Status = &v
}

// GetTrustScore returns the TrustScore field value if set, zero value otherwise.
func (o *Agent) GetTrustScore() int32 {
	if o == nil || IsNil(o.TrustScore) {
		var ret int32
		return ret
	}
	return *o.TrustScore
}

// GetTrustScoreOk returns a tuple with the TrustScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetTrustScoreOk() (*int32, bool) {
	if o == nil || IsNil(o.TrustScore) {
		return nil, false
	}
	return o.TrustScore, true
}

// HasTrustScore returns a boolean if a field has been set.
func (o *Agent) HasTrustScore() bool {
	if o != nil && !IsNil(o.TrustScore) {
		return true
	}

	return false
}

// SetTrustScore gets a reference to the given int32 and assigns it to the TrustScore field.
func (o *Agent) SetTrustScore(v int32) {
	o.TrustScore = &v
}

// GetTrustTier returns the TrustTier field value if set, zero value otherwise.
func (o *Agent) GetTrustTier() string {
	if o == nil || IsNil(o.TrustTier) {
		var ret string
		return ret
	}
	return *o.TrustTier
}

// GetTrustTierOk returns a tuple with the TrustTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetTrustTierOk() (*string, bool) {
	if o == nil || IsNil(o.TrustTier) {
		return nil, false
	}
	return o.TrustTier, true
}

// HasTrustTier returns a boolean if a field has been set.
func (o *Agent) HasTrustTier() bool {
	if o != nil && !IsNil(o.TrustTier) {
		return true
	}

	return false
}

// SetTrustTier gets a reference to the given string and assigns it to the TrustTier field.
func (o *Agent) SetTrustTier(v string) {
	o.TrustTier = &v
}

// GetCertificationLevel returns the CertificationLevel field value if set, zero value otherwise.
func (o *Agent) GetCertificationLevel() string {
	if o == nil || IsNil(o.CertificationLevel) {
		var ret string
		return ret
	}
	return *o.CertificationLevel
}

// GetCertificationLevelOk returns a tuple with the CertificationLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetCertificationLevelOk() (*string, bool) {
	if o == nil || IsNil(o.CertificationLevel) {
		return nil, false
	}
	return o.CertificationLevel, true
}

// HasCertificationLevel returns a boolean if a field has been set.
func (o *Agent) HasCertificationLevel() bool {
	if o != nil && !IsNil(o.CertificationLevel) {
		return true
	}

	return false
}

// SetCertificationLevel gets a reference to the given string and assigns it to the CertificationLevel field.
func (o *Agent) SetCertificationLevel(v string) {
	o.CertificationLevel = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *Agent) GetPublished() bool {
	if o == nil || IsNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetPublishedOk() (*bool, bool) {
	if o == nil || IsNil(o.Published) {
		return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *Agent) HasPublished() bool {
	if o != nil && !IsNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *Agent) SetPublished(v bool) {
	o.Published = &v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *Agent) GetCapabilities() []string {
	if o == nil || IsNil(o.Capabilities) {
		var ret []string
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetCapabilitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *Agent) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []string and assigns it to the Capabilities field.
func (o *Agent) SetCapabilities(v []string) {
	o.Capabilities = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Agent) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Agent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Agent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *Agent) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

func (o Agent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Agent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TrustScore) {
		toSerialize["trust_score"] = o.TrustScore
	}
	if !IsNil(o.TrustTier) {
		toSerialize["trust_tier"] = o.TrustTier
	}
	if !IsNil(o.CertificationLevel) {
		toSerialize["certification_level"] = o.CertificationLevel
	}
	if !IsNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableAgent struct {
	value *Agent
	isSet bool
}

func (v NullableAgent) Get() *Agent {
	return v.value
}

func (v *NullableAgent) Set(val *Agent) {
	v.value = val
	v.isSet = true
}

func (v NullableAgent) IsSet() bool {
	return v.isSet
}

func (v *NullableAgent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgent(val *Agent) *NullableAgent {
	return &NullableAgent{value: val, isSet: true}
}

func (v NullableAgent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


