/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
)

// checks if the ListNotifications200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListNotifications200Response{}

// ListNotifications200Response struct for ListNotifications200Response
type ListNotifications200Response struct {
	Data []map[string]interface{} `json:"data,omitempty"`
	UnreadCount *int32 `json:"unread_count,omitempty"`
}

// NewListNotifications200Response instantiates a new ListNotifications200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListNotifications200Response() *ListNotifications200Response {
	this := ListNotifications200Response{}
	return &this
}

// NewListNotifications200ResponseWithDefaults instantiates a new ListNotifications200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListNotifications200ResponseWithDefaults() *ListNotifications200Response {
	this := ListNotifications200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListNotifications200Response) GetData() []map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListNotifications200Response) GetDataOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListNotifications200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []map[string]interface{} and assigns it to the Data field.
func (o *ListNotifications200Response) SetData(v []map[string]interface{}) {
	o.Data = v
}

// GetUnreadCount returns the UnreadCount field value if set, zero value otherwise.
func (o *ListNotifications200Response) GetUnreadCount() int32 {
	if o == nil || IsNil(o.UnreadCount) {
		var ret int32
		return ret
	}
	return *o.UnreadCount
}

// GetUnreadCountOk returns a tuple with the UnreadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListNotifications200Response) GetUnreadCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UnreadCount) {
		return nil, false
	}
	return o.UnreadCount, true
}

// HasUnreadCount returns a boolean if a field has been set.
func (o *ListNotifications200Response) HasUnreadCount() bool {
	if o != nil && !IsNil(o.UnreadCount) {
		return true
	}

	return false
}

// SetUnreadCount gets a reference to the given int32 and assigns it to the UnreadCount field.
func (o *ListNotifications200Response) SetUnreadCount(v int32) {
	o.UnreadCount = &v
}

func (o ListNotifications200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListNotifications200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.UnreadCount) {
		toSerialize["unread_count"] = o.UnreadCount
	}
	return toSerialize, nil
}

type NullableListNotifications200Response struct {
	value *ListNotifications200Response
	isSet bool
}

func (v NullableListNotifications200Response) Get() *ListNotifications200Response {
	return v.value
}

func (v *NullableListNotifications200Response) Set(val *ListNotifications200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListNotifications200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListNotifications200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListNotifications200Response(val *ListNotifications200Response) *NullableListNotifications200Response {
	return &NullableListNotifications200Response{value: val, isSet: true}
}

func (v NullableListNotifications200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListNotifications200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


