/*
AgentAnchor API

AI Governance Operating System API - Manage agents, trust scores, marketplace, and governance with complete audit trails.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentanchor

import (
	"encoding/json"
)

// checks if the ListMarketplaceListings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMarketplaceListings200Response{}

// ListMarketplaceListings200Response struct for ListMarketplaceListings200Response
type ListMarketplaceListings200Response struct {
	Data []MarketplaceListing `json:"data,omitempty"`
	Meta *PaginationMeta `json:"meta,omitempty"`
}

// NewListMarketplaceListings200Response instantiates a new ListMarketplaceListings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMarketplaceListings200Response() *ListMarketplaceListings200Response {
	this := ListMarketplaceListings200Response{}
	return &this
}

// NewListMarketplaceListings200ResponseWithDefaults instantiates a new ListMarketplaceListings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMarketplaceListings200ResponseWithDefaults() *ListMarketplaceListings200Response {
	this := ListMarketplaceListings200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListMarketplaceListings200Response) GetData() []MarketplaceListing {
	if o == nil || IsNil(o.Data) {
		var ret []MarketplaceListing
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMarketplaceListings200Response) GetDataOk() ([]MarketplaceListing, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListMarketplaceListings200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []MarketplaceListing and assigns it to the Data field.
func (o *ListMarketplaceListings200Response) SetData(v []MarketplaceListing) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListMarketplaceListings200Response) GetMeta() PaginationMeta {
	if o == nil || IsNil(o.Meta) {
		var ret PaginationMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListMarketplaceListings200Response) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListMarketplaceListings200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given PaginationMeta and assigns it to the Meta field.
func (o *ListMarketplaceListings200Response) SetMeta(v PaginationMeta) {
	o.Meta = &v
}

func (o ListMarketplaceListings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMarketplaceListings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableListMarketplaceListings200Response struct {
	value *ListMarketplaceListings200Response
	isSet bool
}

func (v NullableListMarketplaceListings200Response) Get() *ListMarketplaceListings200Response {
	return v.value
}

func (v *NullableListMarketplaceListings200Response) Set(val *ListMarketplaceListings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListMarketplaceListings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListMarketplaceListings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMarketplaceListings200Response(val *ListMarketplaceListings200Response) *NullableListMarketplaceListings200Response {
	return &NullableListMarketplaceListings200Response{value: val, isSet: true}
}

func (v NullableListMarketplaceListings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMarketplaceListings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


