/**
 * Tests for ZKVerifierService
 *
 * Validates zero-knowledge proof verification including:
 * - Single proof verification (valid, invalid structure, expired, unknown circuit)
 * - Batch verification (all valid, mixed, empty)
 * - Verification result caching (hit, clear, stats)
 * - Proof expiration checks (isExpired, getRemainingValidity)
 * - Serialized proof deserialization and verification
 *
 * The verifier uses simplified Schnorr verification: proofs must be >= 96 bytes
 * with 32-byte commitment, challenge, and response segments. Proofs generated
 * by ZKProverService satisfy these constraints and pass cryptographic checks.
 *
 * @module security/zkp/__tests__/verifier.test
 */

import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';

vi.mock('../../../common/logger.js', () => ({
  createLogger: () => ({
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  }),
}));

vi.mock('../../../common/errors.js', () => ({
  VorionError: class VorionError extends Error {
    code = 'VORION_ERROR';
    statusCode = 500;
    constructor(message: string, details?: Record<string, unknown>) {
      super(message);
    }
  },
}));

vi.mock('../../../common/metrics-registry.js', () => ({
  vorionRegistry: { registerMetric: vi.fn() },
}));

vi.mock('prom-client', () => ({
  Counter: class {
    inc = vi.fn();
    constructor() {}
  },
  Histogram: class {
    observe = vi.fn();
    constructor() {}
  },
  Gauge: class {
    set = vi.fn();
    constructor() {}
  },
}));

import { ZKVerifierService, VerificationError } from '../verifier.js';
import { ZKProverService } from '../prover.js';
import type { ZKProof, SerializedZKProof } from '../types.js';
import { VerificationErrorCode, ZKCircuitType } from '../types.js';

// =============================================================================
// HELPERS
// =============================================================================

/**
 * Generate a real proof using the prover so it passes cryptographic verification.
 */
async function createValidProof(circuit = 'age_verification'): Promise<ZKProof> {
  const prover = new ZKProverService({ includeMetadata: true });
  return prover.generateAgeProof(new Date('1990-01-01'), 18);
}

/**
 * Build a mock proof with controllable fields.
 * The 96-byte proof passes structural checks but may not pass full crypto
 * unless generated through the prover.
 */
function createMockProof(overrides: Partial<ZKProof> = {}): ZKProof {
  return {
    proof: new Uint8Array(96),
    publicInputs: [Date.now().toString(), '18'],
    circuit: 'age_verification',
    timestamp: new Date(),
    expiresAt: new Date(Date.now() + 3600000),
    proofId: '12345678-1234-4234-8234-123456789abc',
    version: '1.0.0',
    ...overrides,
  };
}

/**
 * Serialize a ZKProof into the format accepted by verifySerializedProof.
 */
function serializeProof(proof: ZKProof): SerializedZKProof {
  // Convert Uint8Array to base64 via binary string
  const binaryString = String.fromCharCode(...proof.proof);
  const base64 = btoa(binaryString);

  return {
    proof: base64,
    publicInputs: proof.publicInputs,
    circuit: proof.circuit,
    timestamp: proof.timestamp.toISOString(),
    expiresAt: proof.expiresAt?.toISOString(),
    metadata: proof.metadata,
    version: proof.version,
    proofId: proof.proofId,
  };
}

// =============================================================================
// TESTS
// =============================================================================

describe('ZKVerifierService', () => {
  let verifier: ZKVerifierService;

  beforeEach(() => {
    verifier = new ZKVerifierService({
      enableCaching: true,
      rejectExpiredProofs: true,
      clockSkewTolerance: 5000,
    });
  });

  afterEach(() => {
    verifier.destroy();
  });

  // ---------------------------------------------------------------------------
  // Proof Verification
  // ---------------------------------------------------------------------------

  describe('verify', () => {
    it('verifies a valid proof generated by ZKProverService', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
      expect(result.circuit).toBe(ZKCircuitType.AGE_VERIFICATION);
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(result.publicInputs).toEqual(proof.publicInputs);
      expect(result.verificationTimeMs).toBeGreaterThanOrEqual(0);
      expect(result.error).toBeUndefined();
      expect(result.errorCode).toBeUndefined();
    });

    it('rejects proof with invalid structure (proof not Uint8Array)', async () => {
      const proof = createMockProof({
        proof: 'not-a-uint8array' as unknown as Uint8Array,
      });
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PROOF_FORMAT);
      expect(result.error).toBeDefined();
    });

    it('rejects proof with too-short proof bytes (< 96)', async () => {
      const proof = createMockProof({
        proof: new Uint8Array(48),
      });
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
    });

    it('rejects expired proof when rejectExpiredProofs is true', async () => {
      const proof = await createValidProof();
      // Set expiresAt to the past, beyond clock skew tolerance
      proof.expiresAt = new Date(Date.now() - 60000);

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.PROOF_EXPIRED);
      expect(result.error).toContain('expired');
    });

    it('allows non-expired proof', async () => {
      const proof = await createValidProof();
      // Ensure it expires well into the future
      proof.expiresAt = new Date(Date.now() + 7200000);

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
    });

    it('rejects proof with unknown circuit type', async () => {
      const proof = await createValidProof();
      proof.circuit = 'nonexistent_circuit_type';

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.UNKNOWN_CIRCUIT);
      expect(result.error).toContain('Unknown circuit');
    });
  });

  // ---------------------------------------------------------------------------
  // Batch Verification
  // ---------------------------------------------------------------------------

  describe('verifyBatch', () => {
    it('verifyBatch with all valid proofs returns allValid=true', async () => {
      const proof1 = await createValidProof();
      const proof2 = await createValidProof();

      const batch = await verifier.verifyBatch([proof1, proof2]);

      expect(batch.allValid).toBe(true);
      expect(batch.totalProofs).toBe(2);
      expect(batch.validProofs).toBe(2);
      expect(batch.results).toHaveLength(2);
      expect(batch.totalTimeMs).toBeGreaterThanOrEqual(0);
      expect(batch.completedAt).toBeInstanceOf(Date);
    });

    it('verifyBatch with mix of valid/invalid returns allValid=false with correct counts', async () => {
      const validProof = await createValidProof();
      const invalidProof = createMockProof({
        proof: 'bad' as unknown as Uint8Array,
      });

      const batch = await verifier.verifyBatch([validProof, invalidProof]);

      expect(batch.allValid).toBe(false);
      expect(batch.totalProofs).toBe(2);
      expect(batch.validProofs).toBe(1);
      expect(batch.results).toHaveLength(2);
      expect(batch.results[0]!.valid).toBe(true);
      expect(batch.results[1]!.valid).toBe(false);
    });

    it('verifyBatch with empty array returns allValid=true and totalProofs=0', async () => {
      const batch = await verifier.verifyBatch([]);

      expect(batch.allValid).toBe(true);
      expect(batch.totalProofs).toBe(0);
      expect(batch.validProofs).toBe(0);
      expect(batch.results).toHaveLength(0);
      expect(batch.totalTimeMs).toBe(0);
    });
  });

  // ---------------------------------------------------------------------------
  // Caching
  // ---------------------------------------------------------------------------

  describe('caching', () => {
    it('second verification of same proof returns fromCache=true when caching enabled', async () => {
      const proof = await createValidProof();

      const first = await verifier.verify(proof);
      expect(first.valid).toBe(true);
      expect(first.fromCache).toBe(false);

      const second = await verifier.verify(proof);
      expect(second.valid).toBe(true);
      expect(second.fromCache).toBe(true);
    });

    it('clearCache resets cache size to 0', async () => {
      const proof = await createValidProof();
      await verifier.verify(proof);

      expect(verifier.getCacheStats().size).toBeGreaterThan(0);

      verifier.clearCache();

      expect(verifier.getCacheStats().size).toBe(0);
    });

    it('getCacheStats returns correct size and enabled state', async () => {
      // Initially empty
      const stats = verifier.getCacheStats();
      expect(stats.size).toBe(0);
      expect(stats.enabled).toBe(true);

      // After verifying a valid proof the cache grows
      const proof = await createValidProof();
      await verifier.verify(proof);

      const afterStats = verifier.getCacheStats();
      expect(afterStats.size).toBe(1);
      expect(afterStats.enabled).toBe(true);
    });
  });

  // ---------------------------------------------------------------------------
  // Expiration
  // ---------------------------------------------------------------------------

  describe('isExpired', () => {
    it('returns false for non-expired proof', () => {
      const proof = createMockProof({
        expiresAt: new Date(Date.now() + 3600000),
      });

      expect(verifier.isExpired(proof)).toBe(false);
    });

    it('returns true for expired proof', () => {
      const proof = createMockProof({
        expiresAt: new Date(Date.now() - 60000),
      });

      expect(verifier.isExpired(proof)).toBe(true);
    });
  });

  describe('getRemainingValidity', () => {
    it('returns positive number for non-expired proof', () => {
      const proof = createMockProof({
        expiresAt: new Date(Date.now() + 3600000),
      });

      const remaining = verifier.getRemainingValidity(proof);

      expect(remaining).not.toBeNull();
      expect(remaining).toBeGreaterThan(0);
      // Should be close to 3600000 but not exact due to timing
      expect(remaining!).toBeLessThanOrEqual(3600000);
    });

    it('returns 0 for expired proof', () => {
      const proof = createMockProof({
        expiresAt: new Date(Date.now() - 60000),
      });

      const remaining = verifier.getRemainingValidity(proof);

      expect(remaining).toBe(0);
    });

    it('returns null for proof without expiresAt', () => {
      const proof = createMockProof({ expiresAt: undefined });

      const remaining = verifier.getRemainingValidity(proof);

      expect(remaining).toBeNull();
    });
  });

  // ---------------------------------------------------------------------------
  // Serialized Proofs
  // ---------------------------------------------------------------------------

  describe('verifySerializedProof', () => {
    it('deserializes and verifies a valid proof', async () => {
      const proof = await createValidProof();
      const serialized = serializeProof(proof);

      const result = await verifier.verifySerializedProof(serialized);

      expect(result.valid).toBe(true);
      expect(result.circuit).toBe(proof.circuit);
      expect(result.publicInputs).toEqual(proof.publicInputs);
    });
  });

  // ---------------------------------------------------------------------------
  // Mutation-killing: Result object assertions
  // ---------------------------------------------------------------------------

  describe('result object assertions (mutation-killing)', () => {
    it('valid result has verifiedAt as a Date', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
      expect(result.verifiedAt).toBeInstanceOf(Date);
      // verifiedAt should be very recent (within last 5 seconds)
      expect(result.verifiedAt.getTime()).toBeGreaterThanOrEqual(Date.now() - 5000);
      expect(result.verifiedAt.getTime()).toBeLessThanOrEqual(Date.now() + 1000);
    });

    it('valid result has verificationTimeMs >= 0 and < 10000', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
      expect(result.verificationTimeMs).toBeDefined();
      expect(result.verificationTimeMs).toBeGreaterThanOrEqual(0);
      expect(result.verificationTimeMs).toBeLessThan(10000);
    });

    it('valid result.circuit matches the proof.circuit', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
      expect(result.circuit).toBe(proof.circuit);
      expect(result.circuit).toBe(ZKCircuitType.AGE_VERIFICATION);
    });

    it('valid result.publicInputs matches proof.publicInputs', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
      expect(result.publicInputs).toEqual(proof.publicInputs);
      expect(result.publicInputs).toHaveLength(2);
    });

    it('invalid result also has verifiedAt and verificationTimeMs populated', async () => {
      const proof = createMockProof({ proof: 'bad' as unknown as Uint8Array });
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(result.verificationTimeMs).toBeDefined();
      expect(result.verificationTimeMs).toBeGreaterThanOrEqual(0);
    });
  });

  // ---------------------------------------------------------------------------
  // Mutation-killing: Clock skew boundary tests
  // ---------------------------------------------------------------------------

  describe('clock skew boundary tests (mutation-killing)', () => {
    it('proof with expiresAt just within clock skew tolerance still passes', async () => {
      const proof = await createValidProof();
      // Set expiresAt to (now - clockSkewTolerance + 1000ms), so it is expired but within tolerance
      // clockSkewTolerance for this test verifier = 5000ms
      proof.expiresAt = new Date(Date.now() - 5000 + 2000); // 3 seconds ago, tolerance is 5s

      const result = await verifier.verify(proof);

      // Should pass because now (Date.now()) <= expiresAt.getTime() + clockSkewTolerance
      expect(result.valid).toBe(true);
    });

    it('proof with expiresAt beyond clock skew tolerance fails', async () => {
      const proof = await createValidProof();
      // Set expiresAt to (now - clockSkewTolerance - 1000ms), well beyond tolerance
      proof.expiresAt = new Date(Date.now() - 5000 - 2000); // 7 seconds ago, tolerance is 5s

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.PROOF_EXPIRED);
    });

    it('proof with expiresAt exactly at tolerance boundary (tight)', async () => {
      const proof = await createValidProof();
      // Set expiresAt to (now - clockSkewTolerance), right at the boundary
      // now > expiresAt + tolerance would be now > (now - 5000) + 5000 = now > now, which is false => valid
      proof.expiresAt = new Date(Date.now() - 4999); // just barely within tolerance

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
    });
  });

  // ---------------------------------------------------------------------------
  // Mutation-killing: Structure validation
  // ---------------------------------------------------------------------------

  describe('structure validation (mutation-killing)', () => {
    it('proof with circuit: null is invalid', async () => {
      const proof = createMockProof({ circuit: null as unknown as string });
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PROOF_FORMAT);
    });

    it('proof with timestamp: null is invalid', async () => {
      const proof = createMockProof({ timestamp: null as unknown as Date });
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PROOF_FORMAT);
    });

    it('proof with empty publicInputs array still passes structure check', async () => {
      // Empty publicInputs is structurally valid (Array.isArray([]) is true)
      // but may fail circuit-level validation
      const proof = await createValidProof();
      proof.publicInputs = [];

      const result = await verifier.verify(proof);

      // Should fail at circuit-level public input validation, not structure
      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PUBLIC_INPUTS);
    });

    it('proof with publicInputs not an array causes a Zod validation error', async () => {
      const proof = createMockProof({ publicInputs: 'not-an-array' as unknown as string[] });
      // The verifier detects the invalid structure but when it builds the result
      // object it passes the non-array publicInputs through, causing the result
      // schema validation (Zod) to throw. This surfaces as an unhandled ZodError.
      await expect(verifier.verify(proof)).rejects.toThrow();
    });
  });

  // ---------------------------------------------------------------------------
  // Mutation-killing: Cache behavior
  // ---------------------------------------------------------------------------

  describe('cache behavior (mutation-killing)', () => {
    it('invalid proof is NOT cached - verifying twice both return fromCache=false', async () => {
      const proof = createMockProof({ proof: 'bad' as unknown as Uint8Array });

      const first = await verifier.verify(proof);
      expect(first.valid).toBe(false);
      expect(first.fromCache).toBe(false);

      const second = await verifier.verify(proof);
      expect(second.valid).toBe(false);
      expect(second.fromCache).toBe(false);
    });

    it('cache eviction occurs when maxSize is exceeded', async () => {
      // Create a verifier with a tiny cache (maxSize=2)
      const smallVerifier = new ZKVerifierService({
        enableCaching: true,
        maxCacheSize: 2,
        cacheTTL: 60000,
        rejectExpiredProofs: true,
        clockSkewTolerance: 5000,
      });

      try {
        // Generate and verify 3 distinct proofs to overflow the cache
        const proof1 = await createValidProof();
        const proof2 = await createValidProof();
        const proof3 = await createValidProof();

        await smallVerifier.verify(proof1);
        await smallVerifier.verify(proof2);

        expect(smallVerifier.getCacheStats().size).toBe(2);

        await smallVerifier.verify(proof3);

        // After inserting the third, the oldest should have been evicted
        expect(smallVerifier.getCacheStats().size).toBe(2);
      } finally {
        smallVerifier.destroy();
      }
    });

    it('caching disabled means fromCache is always false', async () => {
      const noCacheVerifier = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: true,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();

        const first = await noCacheVerifier.verify(proof);
        expect(first.valid).toBe(true);
        expect(first.fromCache).toBe(false);

        const second = await noCacheVerifier.verify(proof);
        expect(second.valid).toBe(true);
        expect(second.fromCache).toBe(false);

        expect(noCacheVerifier.getCacheStats().enabled).toBe(false);
        expect(noCacheVerifier.getCacheStats().size).toBe(0);
      } finally {
        noCacheVerifier.destroy();
      }
    });
  });

  // ---------------------------------------------------------------------------
  // Mutation-killing: isExpired with no expiresAt
  // ---------------------------------------------------------------------------

  describe('isExpired edge cases (mutation-killing)', () => {
    it('returns false when proof has no expiresAt (never expires)', () => {
      const proof = createMockProof({ expiresAt: undefined });

      expect(verifier.isExpired(proof)).toBe(false);
    });

    it('getRemainingValidity returns null when proof has no expiresAt', () => {
      const proof = createMockProof({ expiresAt: undefined });

      expect(verifier.getRemainingValidity(proof)).toBeNull();
    });
  });

  // ---------------------------------------------------------------------------
  // Mutation-killing: Serialized proof with tampered data
  // ---------------------------------------------------------------------------

  describe('verifySerializedProof tampered data (mutation-killing)', () => {
    it('tampered base64 proof data fails verification', async () => {
      const proof = await createValidProof();
      const serialized = serializeProof(proof);

      // Tamper with the base64 proof data by flipping characters
      const tamperedProof = serialized.proof
        .split('')
        .map((c, i) => (i % 3 === 0 ? String.fromCharCode(c.charCodeAt(0) ^ 1) : c))
        .join('');

      const result = await verifier.verifySerializedProof({
        ...serialized,
        proof: tamperedProof,
      });

      // Either deserialization fails or crypto verification fails
      expect(result.valid).toBe(false);
    });

    it('completely invalid base64 string fails with INVALID_PROOF_FORMAT', async () => {
      const proof = await createValidProof();
      const serialized = serializeProof(proof);

      const result = await verifier.verifySerializedProof({
        ...serialized,
        proof: '!!!not-base64!!!',
      });

      expect(result.valid).toBe(false);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PROOF_FORMAT);
    });

    it('serialized proof with tampered circuit fails verification', async () => {
      const proof = await createValidProof();
      const serialized = serializeProof(proof);

      const result = await verifier.verifySerializedProof({
        ...serialized,
        circuit: 'tampered_circuit_name',
      });

      expect(result.valid).toBe(false);
    });

    it('serialized proof with tampered publicInputs fails verification', async () => {
      const proof = await createValidProof();
      const serialized = serializeProof(proof);

      const result = await verifier.verifySerializedProof({
        ...serialized,
        publicInputs: ['tampered', 'inputs'],
      });

      expect(result.valid).toBe(false);
    });
  });

  // ===========================================================================
  // MUTATION-KILLING TESTS — Appended to target 66 survived mutants
  // ===========================================================================

  // -------------------------------------------------------------------------
  // A. Cache TTL and expiry (L125, L133, L150)
  // Kills: ArrowFunction→undefined (L125 cleanup interval, L133 map callback),
  //        MethodExpression Math.max→Math.min (L125),
  //        ConditionalExpression→false / EqualityOperator >= vs > (L150)
  // -------------------------------------------------------------------------
  describe('cache TTL and expiry (mutation-killing)', () => {
    it('cache entries expire after TTL — second lookup misses after TTL passes', async () => {
      // Use a very short TTL so we can test expiry
      const shortTTLVerifier = new ZKVerifierService({
        enableCaching: true,
        maxCacheSize: 100,
        cacheTTL: 50, // 50ms TTL
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();

        const first = await shortTTLVerifier.verify(proof);
        expect(first.valid).toBe(true);
        expect(first.fromCache).toBe(false);

        // Verify it IS cached immediately
        const cached = await shortTTLVerifier.verify(proof);
        expect(cached.fromCache).toBe(true);

        // Wait for TTL to expire
        await new Promise(resolve => setTimeout(resolve, 100));

        // Now the cache entry should have expired
        const afterExpiry = await shortTTLVerifier.verify(proof);
        // Kills L150 mutation: if the expiry check (Date.now() > entry.expiresAt)
        // were replaced with "false", we'd still get fromCache=true
        expect(afterExpiry.fromCache).toBe(false);
      } finally {
        shortTTLVerifier.destroy();
      }
    });

    it('cache cleanup interval fires and removes expired entries', async () => {
      // Use a very short TTL so cleanup runs quickly
      // Math.min(ttl, 60000) means cleanup interval = min(30, 60000) = 30ms
      // If mutated to Math.max, cleanup interval = max(30, 60000) = 60000ms (never fires in test)
      const shortTTLVerifier = new ZKVerifierService({
        enableCaching: true,
        maxCacheSize: 100,
        cacheTTL: 30, // 30ms TTL — cleanup interval = Math.min(30, 60000) = 30ms
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();

        await shortTTLVerifier.verify(proof);
        expect(shortTTLVerifier.getCacheStats().size).toBe(1);

        // Wait long enough for TTL to expire AND cleanup interval to fire
        // cleanup interval = Math.min(30, 60000) = 30ms; if mutated to Math.max = 60000ms
        await new Promise(resolve => setTimeout(resolve, 120));

        // After cleanup, the cache should be empty
        // Kills L125 Math.min→Math.max: with Math.max(30, 60000)=60000, cleanup never fires
        // Kills L125 ArrowFunction→undefined: cleanup callback becomes noop
        // Kills L133 ArrowFunction→undefined: computeKey map callback broken means key = NaN
        expect(shortTTLVerifier.getCacheStats().size).toBe(0);
      } finally {
        shortTTLVerifier.destroy();
      }
    });

    it('cache expiry boundary: entry at exactly expiresAt is still expired with >', async () => {
      // Tests the `>` operator on L150: Date.now() > entry.expiresAt
      // With >=, an entry where Date.now() === expiresAt would also be expired
      // With >, it would NOT be expired
      // We can't test the exact boundary easily in real time, but we can test
      // that an entry whose expiresAt is in the past is removed
      const shortTTLVerifier = new ZKVerifierService({
        enableCaching: true,
        maxCacheSize: 100,
        cacheTTL: 1, // 1ms TTL — expires almost immediately
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();

        await shortTTLVerifier.verify(proof);
        expect(shortTTLVerifier.getCacheStats().size).toBe(1);

        // Wait enough for TTL to pass
        await new Promise(resolve => setTimeout(resolve, 10));

        // Attempt to get from cache — should miss because expired
        const result = await shortTTLVerifier.verify(proof);
        expect(result.fromCache).toBe(false);
      } finally {
        shortTTLVerifier.destroy();
      }
    });

    it('cached result includes cacheExpiresAt as a Date', async () => {
      const proof = await createValidProof();

      await verifier.verify(proof);
      const cached = await verifier.verify(proof);

      expect(cached.fromCache).toBe(true);
      // Kills ObjectLiteral mutation on L161-165: if result were {}, cacheExpiresAt would be undefined
      expect(cached.cacheExpiresAt).toBeInstanceOf(Date);
      expect(cached.cacheExpiresAt!.getTime()).toBeGreaterThan(Date.now() - 1000);
    });
  });

  // -------------------------------------------------------------------------
  // B. ArithmeticOperator timing mutations (L293, L295, L359, L409)
  // Kills: performance.now() + startTime instead of -,
  //        durationMs * 1000 instead of / 1000
  // -------------------------------------------------------------------------
  describe('timing arithmetic (mutation-killing)', () => {
    it('cached verification durationMs is small (not huge from + instead of -)', async () => {
      const proof = await createValidProof();

      // First verify to populate cache
      await verifier.verify(proof);

      // Second verify from cache
      const cached = await verifier.verify(proof);

      // Kills L293: performance.now() + startTime would yield ~2x the absolute timestamp
      // (e.g. 30000+ ms) instead of a small diff
      expect(cached.verificationTimeMs).toBeDefined();
      expect(cached.verificationTimeMs).toBeGreaterThanOrEqual(0);
      expect(cached.verificationTimeMs!).toBeLessThan(5000);
    });

    it('verify() result verificationTimeMs is in milliseconds (not microseconds or seconds)', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      // Kills L295: durationMs * 1000 instead of / 1000 would make observe() get a huge value,
      // but we check verificationTimeMs which is set in recordAndReturn
      // Kills L359: performance.now() + startTime would yield a huge value
      expect(result.verificationTimeMs).toBeDefined();
      expect(result.verificationTimeMs).toBeGreaterThanOrEqual(0);
      // A normal verify should take < 1 second; * 1000 mutation would give e.g. 50000
      expect(result.verificationTimeMs!).toBeLessThan(5000);
    });

    it('batch totalTimeMs is reasonable (not astronomical from + instead of -)', async () => {
      const proof1 = await createValidProof();
      const proof2 = await createValidProof();

      const batch = await verifier.verifyBatch([proof1, proof2]);

      // Kills L409: performance.now() + startTime would produce a huge number
      expect(batch.totalTimeMs).toBeGreaterThanOrEqual(0);
      expect(batch.totalTimeMs).toBeLessThan(10000);
    });

    it('individual batch results each have reasonable verificationTimeMs', async () => {
      const proof1 = await createValidProof();
      const proof2 = await createValidProof();

      const batch = await verifier.verifyBatch([proof1, proof2]);

      for (const result of batch.results) {
        expect(result.verificationTimeMs).toBeDefined();
        expect(result.verificationTimeMs).toBeGreaterThanOrEqual(0);
        expect(result.verificationTimeMs!).toBeLessThan(5000);
      }
    });
  });

  // -------------------------------------------------------------------------
  // C. ObjectLiteral mutations (18 survived)
  // Kills: return {} instead of actual object — assert ALL expected fields
  // -------------------------------------------------------------------------
  describe('result object completeness (mutation-killing ObjectLiteral)', () => {
    it('valid verification result has all expected fields defined', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      // Each of these kills an ObjectLiteral mutation that returns {}
      expect(result).toHaveProperty('valid');
      expect(result).toHaveProperty('circuit');
      expect(result).toHaveProperty('verifiedAt');
      expect(result).toHaveProperty('publicInputs');
      expect(result).toHaveProperty('verificationTimeMs');
      expect(result).toHaveProperty('fromCache');

      expect(result.valid).toBe(true);
      expect(typeof result.circuit).toBe('string');
      expect(result.circuit.length).toBeGreaterThan(0);
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(Array.isArray(result.publicInputs)).toBe(true);
      expect(typeof result.verificationTimeMs).toBe('number');
      expect(typeof result.fromCache).toBe('boolean');
    });

    it('invalid result from structure validation has valid=false, error, and errorCode', async () => {
      const proof = createMockProof({ proof: 'bad' as unknown as Uint8Array });
      const result = await verifier.verify(proof);

      // Kills ObjectLiteral on L541-548 (validateProofStructure invalid result)
      expect(result.valid).toBe(false);
      expect(typeof result.error).toBe('string');
      expect(result.error!.length).toBeGreaterThan(0);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PROOF_FORMAT);
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(result.verificationTimeMs).toBeDefined();
      expect(typeof result.verificationTimeMs).toBe('number');
    });

    it('expired proof result has all fields including error and errorCode', async () => {
      const proof = await createValidProof();
      proof.expiresAt = new Date(Date.now() - 60000);

      const result = await verifier.verify(proof);

      // Kills ObjectLiteral on L312-319 (expired proof result)
      expect(result.valid).toBe(false);
      expect(result.circuit).toBe(proof.circuit);
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(Array.isArray(result.publicInputs)).toBe(true);
      expect(result.error).toBe('Proof has expired');
      expect(result.errorCode).toBe(VerificationErrorCode.PROOF_EXPIRED);
      expect(typeof result.verificationTimeMs).toBe('number');
      expect(typeof result.fromCache).toBe('boolean');
    });

    it('unknown circuit result has all fields including error string', async () => {
      const proof = await createValidProof();
      proof.circuit = 'nonexistent_circuit';

      const result = await verifier.verify(proof);

      // Kills ObjectLiteral on L327-334 (unknown circuit result)
      expect(result.valid).toBe(false);
      expect(result.circuit).toBe('nonexistent_circuit');
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(Array.isArray(result.publicInputs)).toBe(true);
      expect(result.error).toContain('Unknown circuit');
      expect(result.errorCode).toBe(VerificationErrorCode.UNKNOWN_CIRCUIT);
    });

    it('invalid public inputs result has all fields', async () => {
      const proof = await createValidProof();
      proof.publicInputs = [];

      const result = await verifier.verify(proof);

      // Kills ObjectLiteral on L340-348 (invalid public inputs result)
      expect(result.valid).toBe(false);
      expect(result.circuit).toBe(proof.circuit);
      expect(result.error).toContain('Invalid public inputs');
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PUBLIC_INPUTS);
      expect(result.verifiedAt).toBeInstanceOf(Date);
    });

    it('crypto verification result has verificationTimeMs field set', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      // Kills ObjectLiteral on L354-362 (crypto verification result)
      expect(result.valid).toBe(true);
      expect(result.verificationTimeMs).toBeDefined();
      expect(result.verificationTimeMs!).toBeGreaterThanOrEqual(0);
      // valid proof should NOT have error/errorCode
      expect(result.error).toBeUndefined();
      expect(result.errorCode).toBeUndefined();
    });

    it('error catch block result (L369) has valid=false and error message', async () => {
      // We need to trigger the catch block in verify()
      // One way: mock verifyProofCrypto to throw
      // Since verifyProofCrypto is private, we can trigger it by creating a proof
      // that passes structure validation but causes crypto.subtle to fail
      // However, that's hard. Instead we test via the error result path by
      // making the circuit's validatePublicInputs throw.
      // Actually, the simplest approach: check that a proof throwing internally
      // returns the error shape.
      // Let's just verify the existing error handling via a known path:
      // a proof that triggers INTERNAL_ERROR
      const proof = await createValidProof();
      // Monkey-patch to make verifyProofCrypto throw
      const original = (verifier as any).verifyProofCrypto;
      (verifier as any).verifyProofCrypto = async () => {
        throw new Error('Simulated internal error');
      };

      try {
        const result = await verifier.verify(proof);

        // Kills ObjectLiteral on L369-376 and BooleanLiteral L370 (valid: false → true)
        expect(result.valid).toBe(false);
        expect(result.circuit).toBe(proof.circuit);
        expect(result.verifiedAt).toBeInstanceOf(Date);
        expect(Array.isArray(result.publicInputs)).toBe(true);
        expect(result.error).toContain('Simulated internal error');
        expect(result.errorCode).toBe(VerificationErrorCode.INTERNAL_ERROR);
        expect(typeof result.verificationTimeMs).toBe('number');
        expect(typeof result.fromCache).toBe('boolean');
        expect(result.fromCache).toBe(false);
      } finally {
        (verifier as any).verifyProofCrypto = original;
      }
    });

    it('empty batch result has all expected fields (ObjectLiteral L392-399)', async () => {
      const batch = await verifier.verifyBatch([]);

      // Kills ObjectLiteral on L392-399 (empty batch early return)
      expect(batch).toHaveProperty('allValid');
      expect(batch).toHaveProperty('totalProofs');
      expect(batch).toHaveProperty('validProofs');
      expect(batch).toHaveProperty('results');
      expect(batch).toHaveProperty('totalTimeMs');
      expect(batch).toHaveProperty('completedAt');

      expect(batch.allValid).toBe(true);
      expect(batch.totalProofs).toBe(0);
      expect(batch.validProofs).toBe(0);
      expect(Array.isArray(batch.results)).toBe(true);
      expect(batch.results).toHaveLength(0);
      expect(batch.totalTimeMs).toBe(0);
      expect(batch.completedAt).toBeInstanceOf(Date);
    });

    it('non-empty batch result has all expected fields (ObjectLiteral L413-420)', async () => {
      const proof = await createValidProof();
      const batch = await verifier.verifyBatch([proof]);

      // Kills ObjectLiteral on L413-420 (batch result construction)
      expect(batch.allValid).toBe(true);
      expect(batch.totalProofs).toBe(1);
      expect(batch.validProofs).toBe(1);
      expect(Array.isArray(batch.results)).toBe(true);
      expect(batch.results).toHaveLength(1);
      expect(typeof batch.totalTimeMs).toBe('number');
      expect(batch.totalTimeMs).toBeGreaterThanOrEqual(0);
      expect(batch.completedAt).toBeInstanceOf(Date);
    });

    it('serialized proof error result has all expected fields', async () => {
      const result = await verifier.verifySerializedProof({
        proof: '!!!invalid!!!',
        publicInputs: ['a', 'b'],
        circuit: 'age_verification',
        timestamp: new Date().toISOString(),
      });

      // Kills ObjectLiteral on L452-459 (verifySerializedProof catch block)
      expect(result.valid).toBe(false);
      expect(result.circuit).toBe('age_verification');
      expect(result.verifiedAt).toBeInstanceOf(Date);
      expect(Array.isArray(result.publicInputs)).toBe(true);
      expect(result.publicInputs).toEqual(['a', 'b']);
      expect(typeof result.error).toBe('string');
      expect(result.error!.length).toBeGreaterThan(0);
      expect(result.errorCode).toBe(VerificationErrorCode.INVALID_PROOF_FORMAT);
    });
  });

  // -------------------------------------------------------------------------
  // D. Expiry check logic (L307, L311) — rejectExpiredProofs + clock skew
  // Kills: ConditionalExpression→true/false, EqualityOperator > vs >=
  // -------------------------------------------------------------------------
  describe('expiry check logic (mutation-killing)', () => {
    it('rejectExpiredProofs=true + expired proof → rejected', async () => {
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: true,
        clockSkewTolerance: 0, // zero tolerance for precise testing
      });

      try {
        const proof = await createValidProof();
        proof.expiresAt = new Date(Date.now() - 1000); // expired 1 second ago

        const result = await v.verify(proof);

        expect(result.valid).toBe(false);
        expect(result.errorCode).toBe(VerificationErrorCode.PROOF_EXPIRED);
      } finally {
        v.destroy();
      }
    });

    it('rejectExpiredProofs=false + expired proof → accepted (not rejected)', async () => {
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: false,
        clockSkewTolerance: 0,
      });

      try {
        const proof = await createValidProof();
        proof.expiresAt = new Date(Date.now() - 60000); // expired 60s ago

        const result = await v.verify(proof);

        // Kills ConditionalExpression→true on L307: if the condition were always true,
        // this proof would be rejected even with rejectExpiredProofs=false
        expect(result.valid).toBe(true);
        expect(result.errorCode).toBeUndefined();
      } finally {
        v.destroy();
      }
    });

    it('clock skew: proof expired exactly at tolerance → NOT rejected (> not >=)', async () => {
      // L311: now > expiresAt + clockSkewTolerance
      // If now === expiresAt + tolerance, > returns false (not expired)
      // If mutated to >=, it would return true (expired)
      const tolerance = 5000;
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: true,
        clockSkewTolerance: tolerance,
      });

      try {
        const proof = await createValidProof();
        const now = Date.now();
        // Set expiresAt such that now === expiresAt + tolerance
        // expiresAt = now - tolerance
        proof.expiresAt = new Date(now - tolerance);

        const result = await v.verify(proof);

        // With >, now > (now - tolerance) + tolerance = now > now = false → valid
        // With >= mutant, now >= now = true → expired
        // This kills the >= vs > mutant on L311
        expect(result.valid).toBe(true);
      } finally {
        v.destroy();
      }
    });

    it('clock skew: proof expired 1ms beyond tolerance → rejected', async () => {
      const tolerance = 5000;
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: true,
        clockSkewTolerance: tolerance,
      });

      try {
        const proof = await createValidProof();
        const now = Date.now();
        // Set expiresAt so now > expiresAt + tolerance by 1ms
        // expiresAt = now - tolerance - 1
        proof.expiresAt = new Date(now - tolerance - 1);

        const result = await v.verify(proof);

        expect(result.valid).toBe(false);
        expect(result.errorCode).toBe(VerificationErrorCode.PROOF_EXPIRED);
      } finally {
        v.destroy();
      }
    });

    it('zero clockSkewTolerance: just-expired proof is rejected', async () => {
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: true,
        clockSkewTolerance: 0,
      });

      try {
        const proof = await createValidProof();
        proof.expiresAt = new Date(Date.now() - 1); // expired 1ms ago

        const result = await v.verify(proof);

        expect(result.valid).toBe(false);
        expect(result.errorCode).toBe(VerificationErrorCode.PROOF_EXPIRED);
      } finally {
        v.destroy();
      }
    });
  });

  // -------------------------------------------------------------------------
  // E. LogicalOperator mutations (L307) — && vs ||
  // L307: `this.config.rejectExpiredProofs && proof.expiresAt`
  // With ||: would enter the block if EITHER is true
  // -------------------------------------------------------------------------
  describe('logical operator on expiry condition (mutation-killing)', () => {
    it('rejectExpiredProofs=true but proof has NO expiresAt → should pass (not rejected)', async () => {
      // Tests && vs ||: with &&, both must be truthy to enter the expiry block
      // proof.expiresAt is undefined → falsy → block NOT entered → proof passes
      // With || mutant: rejectExpiredProofs=true → truthy → block entered
      // then proof.expiresAt is undefined → accessing undefined.getTime() → crash
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: true,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();
        proof.expiresAt = undefined; // no expiration

        const result = await v.verify(proof);

        // With &&: skips expiry check → proceeds to verify → valid
        // With || mutant: enters expiry block, crashes on undefined.getTime()
        expect(result.valid).toBe(true);
      } finally {
        v.destroy();
      }
    });

    it('rejectExpiredProofs=false + proof HAS expiresAt (in past) → should pass', async () => {
      // With &&: rejectExpiredProofs=false → falsy → block NOT entered → proof passes
      // With || mutant: proof.expiresAt is truthy → block entered → proof rejected
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: false,
        clockSkewTolerance: 0,
      });

      try {
        const proof = await createValidProof();
        proof.expiresAt = new Date(Date.now() - 120000); // expired 2 minutes ago

        const result = await v.verify(proof);

        // With &&: rejectExpiredProofs=false → skip expiry check → valid
        // With || mutant: proof.expiresAt truthy → enters block → would reject
        expect(result.valid).toBe(true);
      } finally {
        v.destroy();
      }
    });

    it('rejectExpiredProofs=false + proof has no expiresAt → should pass', async () => {
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();
        proof.expiresAt = undefined;

        const result = await v.verify(proof);

        expect(result.valid).toBe(true);
      } finally {
        v.destroy();
      }
    });
  });

  // -------------------------------------------------------------------------
  // F. BlockStatement mutations (6 survived)
  // Kills: empty blocks replacing actual error/validation logic
  // -------------------------------------------------------------------------
  describe('block statement mutations (mutation-killing)', () => {
    it('validation failure block actually executes and returns error details', async () => {
      // If the block at L229-230 were replaced with {}, no error result would be set
      const proof = createMockProof({
        proof: 'bad' as unknown as Uint8Array,
        circuit: null as unknown as string,
        timestamp: null as unknown as Date,
      });

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.error).toBeDefined();
      expect(result.error!.length).toBeGreaterThan(0);
      // Should contain multiple error messages joined
      expect(result.error).toContain('Invalid');
    });

    it('cache eviction block actually removes oldest entry', async () => {
      // Kills BlockStatement on cache eviction (L175-179)
      // If the eviction block were empty, cache would grow unbounded
      const tinyVerifier = new ZKVerifierService({
        enableCaching: true,
        maxCacheSize: 1,
        cacheTTL: 60000,
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof1 = await createValidProof();
        const proof2 = await createValidProof();

        await tinyVerifier.verify(proof1);
        expect(tinyVerifier.getCacheStats().size).toBe(1);

        await tinyVerifier.verify(proof2);
        // If eviction block were empty, size would be 2
        expect(tinyVerifier.getCacheStats().size).toBe(1);
      } finally {
        tinyVerifier.destroy();
      }
    });

    it('batch verify processes ALL proofs — none skipped by empty block', async () => {
      const proof1 = await createValidProof();
      const proof2 = await createValidProof();
      const proof3 = await createValidProof();

      const batch = await verifier.verifyBatch([proof1, proof2, proof3]);

      // If the Promise.all block were empty, results would be empty
      expect(batch.results).toHaveLength(3);
      expect(batch.totalProofs).toBe(3);
      expect(batch.validProofs).toBe(3);

      // Each result should be fully populated
      for (const r of batch.results) {
        expect(r.valid).toBe(true);
        expect(r.circuit).toBeDefined();
        expect(r.verifiedAt).toBeInstanceOf(Date);
      }
    });

    it('destroy() block actually clears interval and cache', () => {
      // Kills BlockStatement on destroy (L229-234)
      const v = new ZKVerifierService({
        enableCaching: true,
        cacheTTL: 60000,
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      v.destroy();

      // After destroy, getCacheStats should show size 0
      // The cache is nulled, so getCacheStats returns {size:0, enabled:false} effectively
      const stats = v.getCacheStats();
      expect(stats.size).toBe(0);
    });
  });

  // -------------------------------------------------------------------------
  // G. ArrayDeclaration mutations (5 survived)
  // Kills: publicInputs replaced with [] or results replaced with []
  // -------------------------------------------------------------------------
  describe('array declaration mutations (mutation-killing)', () => {
    it('valid result publicInputs has actual elements (not empty array)', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      // Kills ArrayDeclaration mutation that replaces publicInputs with []
      expect(result.publicInputs.length).toBeGreaterThan(0);
      expect(result.publicInputs).toEqual(proof.publicInputs);
    });

    it('batch results array has correct length matching input proofs', async () => {
      const proofs = [
        await createValidProof(),
        await createValidProof(),
        await createValidProof(),
      ];

      const batch = await verifier.verifyBatch(proofs);

      // Kills ArrayDeclaration mutation that replaces results with []
      expect(batch.results.length).toBe(3);
      expect(batch.totalProofs).toBe(3);
    });

    it('invalid result publicInputs is still populated from proof', async () => {
      const proof = await createValidProof();
      proof.circuit = 'nonexistent_circuit';

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      // Kills ArrayDeclaration: publicInputs should reflect original proof's inputs
      expect(result.publicInputs.length).toBeGreaterThan(0);
      expect(result.publicInputs).toEqual(proof.publicInputs);
    });

    it('structure validation error result publicInputs defaults to [] when missing', async () => {
      // When publicInputs is not an array, validateProofStructure uses proof.publicInputs ?? []
      // This tests that the default [] path works correctly
      const proof = createMockProof({ proof: 'bad' as unknown as Uint8Array });
      const result = await verifier.verify(proof);

      // publicInputs should be the original (valid) array from the mock
      expect(Array.isArray(result.publicInputs)).toBe(true);
    });

    it('expired proof result preserves original publicInputs', async () => {
      const proof = await createValidProof();
      const originalInputs = [...proof.publicInputs];
      proof.expiresAt = new Date(Date.now() - 60000);

      const result = await verifier.verify(proof);

      expect(result.valid).toBe(false);
      expect(result.publicInputs).toEqual(originalInputs);
      expect(result.publicInputs.length).toBeGreaterThan(0);
    });
  });

  // -------------------------------------------------------------------------
  // H. BooleanLiteral (L370) — valid: false in catch block
  // Kills: valid: false → true mutation
  // -------------------------------------------------------------------------
  describe('boolean literal mutations (mutation-killing)', () => {
    it('catch block error result has valid=false (not mutated to true)', async () => {
      // Force the catch block by making verifyProofCrypto throw
      const original = (verifier as any).verifyProofCrypto;
      (verifier as any).verifyProofCrypto = async () => {
        throw new Error('Forced failure');
      };

      try {
        const proof = await createValidProof();
        const result = await verifier.verify(proof);

        // Kills BooleanLiteral L370: valid: false → true
        expect(result.valid).toStrictEqual(false);
        expect(result.valid).not.toBe(true);
      } finally {
        (verifier as any).verifyProofCrypto = original;
      }
    });

    it('valid proof has valid=true (not mutated to false)', async () => {
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toStrictEqual(true);
      expect(result.valid).not.toBe(false);
    });

    it('structure-valid proof returns valid=true from validateProofStructure', async () => {
      // When structure is valid, validateProofStructure returns { valid: true, ... }
      // If BooleanLiteral mutated valid: true → false, the whole chain would fail
      const proof = await createValidProof();
      const result = await verifier.verify(proof);

      expect(result.valid).toBe(true);
      expect(result.errorCode).toBeUndefined();
    });
  });

  // -------------------------------------------------------------------------
  // Additional mutation-killing: ConditionalExpression on L177 (cache size >= maxSize)
  // -------------------------------------------------------------------------
  describe('cache maxSize conditional (mutation-killing)', () => {
    it('cache does not exceed maxSize=1 even after multiple inserts', async () => {
      // Kills ConditionalExpression→true on L177:
      // if true, every insert would evict (cache stays at 0-1 forever, but
      // the eviction logic is always triggered)
      // With the real >=, it only evicts when at capacity
      const v = new ZKVerifierService({
        enableCaching: true,
        maxCacheSize: 1,
        cacheTTL: 60000,
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof1 = await createValidProof();
        await v.verify(proof1);
        expect(v.getCacheStats().size).toBe(1);

        // Adding another should evict the first
        const proof2 = await createValidProof();
        await v.verify(proof2);
        expect(v.getCacheStats().size).toBe(1);

        // Verify proof2 is in cache (not proof1)
        const cached2 = await v.verify(proof2);
        expect(cached2.fromCache).toBe(true);

        // proof1 should NOT be cached anymore
        const rechecked1 = await v.verify(proof1);
        expect(rechecked1.fromCache).toBe(false);
      } finally {
        v.destroy();
      }
    });
  });

  // -------------------------------------------------------------------------
  // Additional mutation-killing: VerificationError class (L87-100)
  // -------------------------------------------------------------------------
  describe('VerificationError class', () => {
    it('VerificationError extends Error with correct properties', () => {
      const err = new VerificationError(
        'test error',
        VerificationErrorCode.INTERNAL_ERROR,
        'test_circuit',
        { detail: 'value' }
      );

      expect(err).toBeInstanceOf(Error);
      expect(err).toBeInstanceOf(VerificationError);
      expect(err.message).toBe('test error');
      expect(err.name).toBe('VerificationError');
      expect(err.errorCode).toBe(VerificationErrorCode.INTERNAL_ERROR);
      expect(err.circuit).toBe('test_circuit');
      expect(err.statusCode).toBe(400);
      expect(err.code).toBe('VERIFICATION_ERROR');
    });

    it('batch verification throws VerificationError on internal failure', async () => {
      // Force the batch to throw from within
      const original = (verifier as any).verify.bind(verifier);
      const v = new ZKVerifierService({
        enableCaching: false,
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      // Monkey-patch verify to throw
      (v as any).verify = async () => {
        throw new Error('Simulated batch failure');
      };

      try {
        const proof = await createValidProof();
        await expect(v.verifyBatch([proof])).rejects.toThrow(VerificationError);
        await expect(v.verifyBatch([proof])).rejects.toThrow('Batch verification failed');
      } finally {
        v.destroy();
      }
    });
  });

  // -------------------------------------------------------------------------
  // Additional mutation-killing: factory function
  // -------------------------------------------------------------------------
  describe('createZKVerifier factory', () => {
    it('creates a functional verifier via factory function', async () => {
      const { createZKVerifier } = await import('../verifier.js');
      const v = createZKVerifier({
        enableCaching: false,
        rejectExpiredProofs: false,
        clockSkewTolerance: 5000,
      });

      try {
        const proof = await createValidProof();
        const result = await v.verify(proof);

        expect(result.valid).toBe(true);
        expect(result.circuit).toBe('age_verification');
      } finally {
        v.destroy();
      }
    });
  });

  // -------------------------------------------------------------------------
  // Additional: isExpired boundary with clockSkewTolerance
  // -------------------------------------------------------------------------
  describe('isExpired with clockSkewTolerance boundaries', () => {
    it('isExpired returns false when exactly at boundary', () => {
      // isExpired: Date.now() > proof.expiresAt.getTime() + this.config.clockSkewTolerance
      // At boundary: now === expiresAt + tolerance → > returns false
      const now = Date.now();
      const proof = createMockProof({
        expiresAt: new Date(now - 5000), // expired 5s ago, tolerance is 5s
      });

      // now > (now - 5000) + 5000 → now > now → false
      expect(verifier.isExpired(proof)).toBe(false);
    });

    it('isExpired returns true when 1ms beyond boundary', () => {
      const now = Date.now();
      const proof = createMockProof({
        expiresAt: new Date(now - 5001), // expired 5.001s ago, tolerance is 5s
      });

      // now > (now - 5001) + 5000 → now > now - 1 → true
      expect(verifier.isExpired(proof)).toBe(true);
    });
  });
});
